### ISSUE TITLE
adding new features [Discussion]

### ISSUE THREAD

**Issue by Jigar3** [mrsaicharan1/PyDic#1]
-Currently the application uses a local JSON data file to get the meanings of the words.
It is possible to use a third-party API like [Oxford Dictionaries](https://developer.oxforddictionaries.com/)
-It also relies on that fact the user has to type in the word in the terminal to get its meaning, but it is possible that the user has the word copied and we could simply used the clipboard word. A similar implementation can be seen here [nltk-dictionary](https://github.com/prav10194/nltk-dictionary)

**Comment by mrsaicharan1** [comment]
That's a good idea Jigar. I will be adding it as one of the many issues.
