### ISSUE TITLE
Add a setup.py and a shellscript to automate installation processes

### ISSUE THREAD

**Issue by rahulkumaran** [mrsaicharan1/PyDic#17]
Currently, the users are required to have the python modules pre installed with them. The program will throw and error if it is not isntalled.
So I'd like to write 2 files:
1) A setup.py that has a list of all dependencies and installs them without the user having to do much work.
2) A shellscript to automate the this process and make the whole program function in a virtual environment as it'll make things easier for the user and won't cause any direct problems to the machine by chance also.

Can you please assign this issue to me with the appropriate labels?

**Comment by pani-vishal** [comment]
Can I take this?

**Comment by mrsaicharan1** [comment]
Yes @falconis

**Comment by rahulkumaran** [comment]
@mrsaicharan1 , since i created this and asked for this issue to be assigned to me first shouldn't i be assigned this?

**Comment by pani-vishal** [comment]
Ohh I thought you were the mentor of the project. It would be great if you worked on it...

**Comment by mrsaicharan1** [comment]
@rahulkumaran Sorry for that! You get the issue! @falconis You can work on the others.

**Comment by rahulkumaran** [comment]
@falconis , I am the mentor of a project but I'm also contributing haha :smile:

**Comment by pani-vishal** [comment]
ohh haha
