### ISSUE TITLE
Integrate voice recognition features

### ISSUE THREAD

**Issue by mrsaicharan1** [mrsaicharan1/PyDic#19]
Integrate an API which gives all the info about a word using your voice.

**Comment by rahulkumaran** [comment]
I'd like to take this up! assign this to me please?

**Comment by rahulkumaran** [comment]
Done coding this! :smile: Once this is assigned I'll send the PR!
Also, please have a look at issue no.17 because I asked for it to be assigned to me before the other guy :P

**Comment by mrsaicharan1** [comment]
@rahulkumaran Your issue! Send PR!

**Comment by rahulkumaran** [comment]
Done @mrsaicharan1 ! Have a look at it whenever you're free :smile:

**Comment by mrsaicharan1** [comment]
@rahulkumaran The application throws exceptions on word query. Re-check any library syntax fault or other errors. Send PR directly.

**Comment by rahulkumaran** [comment]
Okiee I'll take care of this! @saicharan

**Comment by rahulkumaran** [comment]
@mrsaicharan1 **
