### ISSUE TITLE
Package the application properly with a setup file and everything,ready for installation

### ISSUE THREAD

**Issue by mrsaicharan1** [mrsaicharan1/PyDic#20]

**Comment by nityanandagohain** [comment]
For linux ?

**Comment by rahulkumaran** [comment]
I'd like to take this up! can you assign it to me?
also, #17  and this are the same aren't they?

**Comment by mrsaicharan1** [comment]
@rahulkumaran this is assigned to you

**Comment by Anupam-dagar** [comment]
@mrsaicharan1 please reply to questions asked too
