### ISSUE TITLE
Add an antonyms feature

### ISSUE THREAD

**Issue by mrsaicharan1** [mrsaicharan1/PyDic#6]
In addition to the synonyms ,add an antonyms dataset . Integrate commands for CLI.
  

> For this issue,work on another branch.

**Comment by rahulkumaran** [comment]
I'd like to work on this.

**Comment by mrsaicharan1** [comment]
@rahulkumaran this is assigned to you. Go ahead.

**Comment by rahulkumaran** [comment]
Just submitted a PR for the same. Btw I included the PyDictionary API too which solves issue #4 .
