### ISSUE TITLE
Add a proper and formatted documentation 

### ISSUE THREAD

**Issue by mrsaicharan1** [mrsaicharan1/PyDic#7]
Get to know what the heck is going on and write out a documentation on how the application works, APIs used ,steps to setup and other features.

**Comment by AbhiTaker** [comment]
i would like to work on this issue

**Comment by mrsaicharan1** [comment]
Do a pull request. This is assigned to you. Go ahead

**Comment by mrsaicharan1** [comment]
@AbhiTaker
