### ISSUE TITLE
Add a proper structure to the application

### ISSUE THREAD

**Issue by mrsaicharan1** [mrsaicharan1/PyDic#8]
Give the repo an industry style file structure. Add separate folders for tests, modules, views etc.

**Comment by rahulkumaran** [comment]
I'd like to work on this @mrsaicharan1

**Comment by mrsaicharan1** [comment]
@rahulkumaran this is assigned to you. Go ahead.

**Comment by rahulkumaran** [comment]
issue PR #15 for the same!
