### ISSUE TITLE
Add sentence usage examples

### ISSUE THREAD

**Issue by mrsaicharan1** [mrsaicharan1/PyDic#9]
Along with the meaning, also provide an example sentence.

**Comment by namantw** [comment]
@mrsaicharan1 please assign me 😄

**Comment by mrsaicharan1** [comment]
You can work on this. This issue is assigned to you

**Comment by namantw** [comment]
@mrsaicharan1 Can you tell me how I can solve this? I am a bit stuck on where to start :(

**Comment by mrsaicharan1** [comment]
You can find help from the APIs. @namantw
